export const FETCH_PRODUCT = 'FETCH_TASK';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILED = 'FETCH_PRODUCT_FAILED';

export const FILTER_PRODUCT = 'FILTER_PRODUCT';
export const FILTER_PRODUCT_SUCCESS = 'FILTER_PRODUCT_SUCCESS';
export const FILTER_PRODUCT_FAILED = 'FILTER_PRODUCT_FAILED';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';
export const REDIRECT_AFTER_ADD_SUCCESS = '/product-list';

export const SET_PRODUCT_EDITTING = 'SET_PRODUCT_EDITTING';
export const RESET_PRODUCT_EDITTING = 'RESET_PRODUCT_EDITTING';

export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const UPDATE_PRODUCT_SUCCESS = 'UPDATE_PRODUCT_SUCCESS';
export const UPDATE_PRODUCT_FAILED = 'UPDATE_PRODUCT_FAILED';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';
